# -*- coding: utf-8 -*-
"""conversor_temperatura.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Giy1mOc7MtJrIsD7f3i4ZoL3hZeRJPK8
"""

# Conversor de Temperatura
# este programa convierte de Celsius a Fahrenheit y al revés.
# tiene validaciones para que no se rompa si el usuario se equivoca

def celsius_a_fahrenheit(celsius):
      # fórmula, multiplico por 9/5 y le sumo 32
    return celsius * (9 / 5) + 32


def fahrenheit_a_celsius(fahrenheit): # aquí resto 32 y después multiplico por 5/9
    return (fahrenheit - 32) * (5 / 9)


def obtener_numero(mensaje):
    # esta función se encarga de pedir el número y validarlo
    # No deja que pongan texto ni que dejen el campo vacío
    while True:
        try:
            valor = input(mensaje).strip()

            # si solo le dan enter, avisa
            if valor == "":
                print("Oye, no puedes dejarlo vacío.")
                continue

            # Intentamos convertirlo a número (aceptando enteros y decimales)
            return float(valor)

        except ValueError:
            print("Eso no es un número válido. Intenta de nuevo.")


def mostrar_menu():
    # solo imprime el menú
    print("\n" + "=" * 42)
    print("       CONVERSOR DE TEMPERATURA")
    print("=" * 42)
    print("1. Celsius  →  Fahrenheit")
    print("2. Fahrenheit  →  Celsius")
    print("3. Salir del programa")
    print("=" * 42)


def main():
    # Esta es la función principal, aquí corre todo el programa
    while True:
        mostrar_menu()
        opcion = input("Elige una opción (1, 2 o 3): ").strip()

        if opcion == "1":
            # pedimos la temperatura en Celsius
            celsius = obtener_numero("Escribe los grados Celsius: ")
            resultado = celsius_a_fahrenheit(celsius)
            print(f"\n→ {celsius}°C equivalen a {resultado:.2f}°F")

        elif opcion == "2":
            # pedimos la temperatura en Fahrenheit
            fahrenheit = obtener_numero("Escribe los grados Fahrenheit: ")
            resultado = fahrenheit_a_celsius(fahrenheit)
            print(f"\n→ {fahrenheit}°F equivalen a {resultado:.2f}°C")

        elif opcion == "3":
            print("\nListo, gracias por usar el conversor.")
            print("Programa terminado.")
            break

        else:
            print("Opción incorrecta. Solo puedes poner 1, 2 o 3.")


# esto hace que el programa se ejecute solo cuando se corre este archivo, main por el archivo py.
if __name__ == "__main__":
    main()